- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World! --"

    - name: run the new hello module
      hello:
        name: 'Avinash Pawar'
      register: helloout

    - name: dump test output
      debug:
        msg: '{{ helloout }}'
